version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  web:
    build: .
    command: sh -c "gunicorn website_browist.wsgi:application --bind 0.0.0.0:8000" 
    volumes:
      - .:/app
      - ./static_files:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_files:/app/staticfiles
      - ./nginx/browist.conf:/etc/nginx/conf.d/browist.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
