# Generated by Django 5.1.1 on 2024-09-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Errors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FreeDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, unique=True)),
                ("free", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="notes",
            name="data",
        ),
        migrations.RemoveField(
            model_name="notes",
            name="description",
        ),
        migrations.AddField(
            model_name="notes",
            name="date",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="durations",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name="notes",
            name="time",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
