# Generated by Django 5.1.1 on 2024-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
