# Generated by Django 5.1.1 on 2024-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_notes_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="freedate",
            name="now",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
