# Generated by Django 5.1.1 on 2024-10-10 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_freedate_now_alter_notes_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freedate",
            name="now",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 10, 18, 0, 40, 491900, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
