# Generated by Django 5.1.1 on 2024-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_data_notes_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="notes",
            name="description",
        ),
    ]
