# Generated by Django 5.1.1 on 2024-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_freedate_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="date",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="time",
            field=models.CharField(blank=True),
        ),
    ]
