# Generated by Django 5.1.1 on 2024-09-19 08:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_notes_date_alter_notes_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="durations",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
