# Generated by Django 5.1.1 on 2024-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_service_durations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Errors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("description", models.TextField()),
            ],
        ),
    ]
